export default [
  {
    id: 0,
    name: 'Samantha',
    location: 'Russia',
    price: 400,
    image: require('../assets/image_1.png'),
  },
  {
    id: 1,
    name: 'Angelica',
    location: 'Russia',
    price: 440,
    image: require('../assets/image_2.png'),
  },
  {
    id: 2,
    name: 'Selican',
    location: 'Russia',
    price: 500,
    image: require('../assets/image_3.png'),
  },
  {
    id: 3,
    name: 'Bosania',
    location: 'Russia',
    price: 410,
    image: require('../assets/bottom_img_1.png'),
  },
  {
    id: 4,
    name: 'Marinda',
    location: 'Russia',
    price: 477,
    image: require('../assets/bottom_img_2.png'),
  },
  {
    id: 5,
    name: 'Hoa Giấy Bonsai',
    category: 'Hoa',
    location: 'Việt Nam',
    price: 1999000,
    countInStock: '6',
    image: require('../assets/bonsai_1.jpg'),
    description:
      'Hoa giấy mọc thành một nhóm gồm 3 hoa và lá bắc, hình thành cụm ở phần cuối của nhánh. Lá bắc xếp hình tam giác, cách chăm sóc cây hoa giấy thuôn dài/trứng và nhọn đầu dài khoảng 3 – 5 cm. Bông hoa giấy thật sự nhỏ, mỗi cái gắn vào một lá bắc, hình ống phồng ở phần giữa.',
    rating: 5,
  },
  {
    id: 6,
    name: 'Tùng Lá Kim',
    category: 'Phong Thuỷ',
    location: 'Việt Nam',
    price: 1999000,
    countInStock: '5',
    image: require('../assets/bonsai_2.jpg'),
    description:
      'Cây tùng lá kim bonsai này được tạo dáng bay, tán hướng xuống qua miệng chậu đến 80 cm. Dáng này còn được gọi là dáng bán huyền, một dáng cơ bản và phổ biến trong nghệ thuật bonsai. Chậu cây tùng lá kim này có kích thược nhỏ, phù hợp trang trí nhiều nơi, dễ di chuyển, đặt để.',
    rating: 4,
  },
];
